app/base/views.py
from flask import Blueprint, render_template, send_from_directory, request
from app import cache
from app.kevcrablog.models import Post
import settings

base = Blueprint('base', __name__)


@base.route('/')
@cache.cached(timeout=1800)
def index():
    """ Main site index page
    """
    frontpage_posts = Post.query_all()[:4]  # TODO: used to use this, but breaks with 0 blog posts: .slice(0, 3)
    return render_template('index.html', frontpage_posts=frontpage_posts)


@base.route('/about')
@cache.cached(timeout=3600)
def about():
    """ Display the About Me page
    """
    return render_template('about.html', title='About')


@base.route('/projects')
@cache.cached(timeout=3600)
def projects():
    """ Display the Projects page
    """
    return render_template('projects.html', title='Projects')



# Error Handlers and Miscellaneous
@base.app_errorhandler(404)
def page_not_found(e):
    """ Error Code 404 Handler
    """
    return render_template('error/404.html'), 404

@base.app_errorhandler(500)
def server_error(e):
    """ Error Code 500 Handler
    """
    return render_template('error/500.html'), 500

@base.app_errorhandler(Exception)
def unhandled_exception(e):
    # TODO: real error page
    if settings.DEBUG:
        raise e
    return render_template('error/500.html', error=e), 500

app/templates/macros/css.html
{#<link href="{{ url_for('static', filename='css/bootstrap-flatly.min.css') }}" rel="stylesheet" media="screen">#}
{##}
{#<link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/default.min.css">#}
{#<link href="{{ url_for('static', filename='css/font-awesome.css') }}" rel="stylesheet" media="screen">#}
{#<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" media="screen">#}

{% assets "css_all" %}
<link rel="stylesheet" href="{{ ASSET_URL }}" type="text/css">
{% endassets %}
<link href='http://fonts.googleapis.com/css?family=PT+Sans|Fredericka+the+Great' rel='stylesheet' type='text/css'>

app/templates/macros/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

app/templates/macros/forms.html
{% macro render(form) -%}
<fieldset>
{% for field in form %}
{% if field.type in ['CSRFTokenField', 'HiddenField'] %}
  {{ field() }}
{% else %}
  <div class="clearfix {% if field.errors %}error{% endif %}">
    {{ field.label }}
    <div class="input">
      {% if field.name == "body" %}
        {{ field(rows=5, cols=40) }}
      {% else %}
        {{ field() }}
      {% endif %}
      {% if field.errors or field.help_text %}
        <span class="help-inline">
        {% if field.errors %}
          {{ field.errors|join(' ') }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </span>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endfor %}
</fieldset>
{% endmacro %}

app/templates/macros/google_analytics.html
<!-- Google Analytics (gtag.js)-->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C6JWSS5L63"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-C6JWSS5L63');
</script>

app/templates/macros/javascript.html
{% assets "js_all" %}
  <script src="{{ ASSET_URL }}"></script>
{% endassets %}
{{ moment.include_moment() }}

app/templates/macros/navbar.html
{% set navigation_bar = [
    ('blog.index', 'Blog'),
    ('base.projects', 'Projects'),
    ('base.about', 'About')
] -%}

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a href="{{ url_for('base.index') }}" class="navbar-brand">The Kevin Crane</a>
    </div>

    <!-- Navbar Tabs -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        {% for id, caption in navigation_bar %}
          <li{% if id == active_page %} class="active"{% endif %}>
            <a href="{{ url_for(id) }}">{{ caption|e }}</a>
          </li>
        {% endfor %}
      </ul>
      <div class="nav navbar-nav navbar-right">
        <ul class="list-inline">
          <li><a target="_blank" href="https://bsky.app/profile/kcrane.co" title="Bluesky">
            <i class="fa fa-brands fa-bluesky fa-3x"></i></a>
          </li>
          <li><a target="_blank" href="http://www.github.com/kevincrane" class="social-navbar" title="Github">
            <i class="fa fa-brands fa-github fa-3x"></i></a>
          </li>
          <li><a target="_blank" href="https://www.linkedin.com/in/thekevincrane" class="social-navbar" title="LinkedIn">
            <i class="fa fa-brands fa-linkedin fa-3x"></i></a>
          </li>
        </ul>
      </div>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>