app/base/models.py
from flask_user import UserMixin as UserMixin

from app.core import db


class User(db.Model, UserMixin):
    """ Site-wide User model
    :param int id: unique user id
    :param str username: The name of the User
    :param str password: The User's password
    :param bool active: Is this user's account enabled?
    :param str email: The User's email
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False, default='')
    active = db.Column(db.Boolean(), nullable=False, default=True)
    email = db.Column(db.String)

    def __init__(self, username, password, email='', active=True):
        self.username = username
        self.password = password
        self.email = email
        self.active = active

app/base/__init__.py
__author__ = 'kcrane'

app/base/views.py
from flask import Blueprint, render_template, send_from_directory, request
from app import cache
from app.kevcrablog.models import Post
import settings

base = Blueprint('base', __name__)


@base.route('/')
@cache.cached(timeout=1800)
def index():
    """ Main site index page
    """
    frontpage_posts = Post.query_all()[:4]  # TODO: used to use this, but breaks with 0 blog posts: .slice(0, 3)
    return render_template('index.html', frontpage_posts=frontpage_posts)


@base.route('/about')
@cache.cached(timeout=3600)
def about():
    """ Display the About Me page
    """
    return render_template('about.html', title='About')


@base.route('/projects')
@cache.cached(timeout=3600)
def projects():
    """ Display the Projects page
    """
    return render_template('projects.html', title='Projects')



# Error Handlers and Miscellaneous
@base.app_errorhandler(404)
def page_not_found(e):
    """ Error Code 404 Handler
    """
    return render_template('error/404.html'), 404

@base.app_errorhandler(500)
def server_error(e):
    """ Error Code 500 Handler
    """
    return render_template('error/500.html'), 500

@base.app_errorhandler(Exception)
def unhandled_exception(e):
    # TODO: real error page
    if settings.DEBUG:
        raise e
    return render_template('error/500.html', error=e), 500

app/kevcrablog/views.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_paginate import Pagination

from app import cache
from app.base.views import page_not_found
from app.core import db
from app.kevcrablog.forms import CommentForm
from app.kevcrablog.models import Post, Comment
from settings import POSTS_PER_PAGE


blog = Blueprint('blog', __name__, url_prefix='/blog')


def sidebar():
    """ Fetch a dict of information that should be used for each view
        e.g. recent posts, posts by view used in base_blog.html
    """
    recent_posts = Post.query_all().limit(5)
    grouped_by_month = Post.group_by_year_month()
    return recent_posts, grouped_by_month


@blog.route('/')
@blog.route('/index/', methods=['GET', 'POST'])
@blog.route('/index/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600)
def index(page=1):
    """ Display the main page of the blog with the most recent blog posts
        paginated and displayed
    :param int page: Which paginated page of blog entries to display
    """
    posts = Post.query_all().paginate(page, POSTS_PER_PAGE, False)
    pagination = Pagination(page=page, total=posts.total, per_page=POSTS_PER_PAGE,
                            record_name='posts', bs_version=3)
    recent, group_month = sidebar()
    return render_template('kevcrablog/index.html', posts=posts, pagination=pagination,
                           recent_posts=recent, grouped_by_month=group_month, title='Blog')


@blog.route('/post/<int:post_id>-<slug>', methods=['GET', 'POST'])
@cache.cached(timeout=3600)
def view_post(post_id, slug):
    """ Display a full new post, with comments and view count
    :param int post_id: id number of post to display
    :param str slug: slugified version of the post title
    """
    post = Post.query.get(post_id)
    form = CommentForm()
    if not post or post.slug != slug:
        return page_not_found(404)

    if request.method == 'POST' and form.validate_on_submit():
        # Handle new comment, redirect to same post
        new_comment = Comment(body=form.body.data, author=form.author.data)
        post.comments.append(new_comment)
        db.session.commit()
        flash('Your comment is now live!', 'success')
        return redirect(url_for('.view_post', post_id=post_id, slug=slug))

    recent, group_month = sidebar()
    return render_template('kevcrablog/post.html', post=post, title=post.title,
                           recent_posts=recent, grouped_by_month=group_month, form=form)

app/templates/_forms.html
{% macro render(form) -%}
<fieldset>
{% for field in form %}
{% if field.type in ['CSRFTokenField', 'HiddenField'] %}
  {{ field() }}
{% else %}
  <div class="clearfix {% if field.errors %}error{% endif %}">
    {{ field.label }}
    <div class="input">
      {% if field.name == "body" %}
        {{ field(rows=5, cols=40) }}
      {% else %}
        {{ field() }}
      {% endif %}
      {% if field.errors or field.help_text %}
        <span class="help-inline">
        {% if field.errors %}
          {{ field.errors|join(' ') }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </span>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endfor %}
</fieldset>
{% endmacro %}

app/templates/about.html
<!-- Extends base layout -->
{% extends "base.html" %}
{% set active_page = "about" %}

{% block content %}
  <h3>About Kevin</h3>
  <ul>
    <li>Works as a software engineer at Twitter, building cool shit for the storage infrastructure of the
      site.
    </li>
    <li>Graduated from the <em>University of Southern California</em> in 2012 with a B.S. of Computer Science.
    </li>
    <li>Masters of Software Engineering from <em>Carnegie Mellon University</em> in 2013, just for good measure.</li>
    <li>Technology I love to work with:
      <ul>
        <li>Python, Java, C, Hadoop, Pig, cryptography, distributed systems, anything with Linux in it.</li>
      </ul>
    </li>
    <li>I also like water polo, rock climbing, guitar, and long walks on the beach.</li>
    <li>
      Come find me here so we can be friends!
      <ul>
        <a href="https://bsky.app/profile/kcrane.co" class="social-about" style="text-decoration: none" target="_blank">
          <i class="fa fa-brands fa-bluesky"></i> <span class="underline-link"> try to be amusing on Bluesky</span>
        </a><br/>
        <a href="http://www.github.com/kevincrane" class="social-about" style="text-decoration: none" target="_blank">
          <i class="fa fa-brands fa-github"></i> <span class="underline-link">I code things on GitHub.</span>
        </a><br/>
        <a href="https://www.linkedin.com/in/thekevincrane" class="social-about" style="text-decoration: none" target="_blank">
          <i class="fa fa-brands fa-linkedin"></i> <span class="underline-link">I pretend to be professional on LinkedIn.</span>
        </a>
      </ul>
    </li>
    <li>
      <h4>
        If you just came here looking for a resume,
        <a href="{{ url_for('static', filename='Kevin-Crane-Resume.pdf') }}" class="underline-link" target="_blank">
          then look no further</a>!
      </h4>
    </li>
  </ul>

  <h3>About This Site</h3>
  <ul>
    <li>
      Homemade, organic, all-natural website; built with "love".
      <ul>
        <li>Written in Python, powered using the Flask framework.</li>
        <li>Other technical stuff to be added later.</li>
        <li>View the source code for yourself <a href="https://github.com/kevincrane/kevcrablog" class="underline-link">here on GitHub!</a>
        </li>
      </ul>
    </li>
    <li>
      Infrastructure
      <ul>
        <li>Hosted with DigitalOcean</li>
        <li>Running on Ubuntu</li>
        <li>Served by nginx and uwsgi</li>
        <li>No more paying GoDaddy $6/month to host a useless Wordpress site, woo!</li>
      </ul>
    </li>
  </ul>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% if title %}
    <title>{{ title }} | The Kevin Crane</title>
  {% else %}
    <title>The Kevin Crane</title>
  {% endif %}
  {% set active_page = active_page|default('index') -%}

  {% include 'macros/google_analytics.html' %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Kevin Crane's blog and personal playground for side projects. Updated as frequently
      as I can manage with new blog posts and links/demos of my own projects!">
  <meta name="keywords" content="kevin crane kcrane personal site blog projects"/>

  <link rel="author" type="text/plain" href="/humans.txt" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  {% include 'macros/css.html' %}
</head>

<body>
<!-- Bootstrap Navbar -->
{% include 'macros/navbar.html' %}

<div class="container">
  <div class="page-content">
    <div class="col-md-12 col-centered">
      {% include 'macros/flash.html' %}

      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>

<footer>
  <div class="text-center">
    <div class="row">
      <div class="footer-col col-sm-5 col-sm-offset-1">
        <h3>Around the World</h3>
        <p>
          Bay Area, CA<br/>
          &copy; 2025 Kevin Crane
        </p>
      </div>
      <div class="footer-col col-sm-4">
        <h3>Around the Web</h3>
        <ul class="list-inline">
          <li><a target="_blank" href="https://bsky.app/profile/kcrane.co" title="Bluesky">
            <i class="fa fa-fw fa-brands fa-bluesky"></i></a>
          </li>
          <li><a target="_blank" href="http://www.github.com/kevincrane" class="social-navbar" title="Github">
            <i class="fa fa-fw fa-brands fa-github"></i></a>
          </li>
          <li><a target="_blank" href="https://www.linkedin.com/in/thekevincrane" class="social-navbar" title="LinkedIn">
            <i class="fa fa-fw fa-brands fa-linkedin"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

{% include 'macros/javascript.html' %}
{% block js %}
{% endblock %}
</body>
</html>

app/templates/index.html
<!-- Extends base layout -->
{% extends "base.html" %}

{% block content %}
<div itemscope itemtype="http://schema.org/WebPage">
  <header>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <img id="kevin-thizz" src="{{ url_for('static', filename='img/kevin-thizz.png') }}" alt="THIZZIN'" height="150px"/>
        <div class="hero-intro">
          <h1>Hi, I'm Kevin!</h1>
          <div class="hero-intro-text">
            <p>Welcome to my online playground!</p>
          </div>
        </div>
        <img id="kevin-happy" src="{{ url_for('static', filename='img/kevin-happy.png') }}" alt="GRINNIN'" height="150px"/>
      </div>
    </div>
  </header>

  <!-- Blog Posts -->
  <section id="index-blog-preview" itemscope itemtype="http://schema.org/Blog">
    <div class="row">
      <div class="col-sm-12 text-center">
        <hr class="star-primary"/>
        <h2 itemprop="headline">Recent Blog Posts</h2>
      </div>
    </div>
    <div class="row">
      {% if frontpage_posts %}
        {% with post=frontpage_posts[0] %}
          <!-- Generate a preview of each blog post -->
          <div class="row">
            <!-- Newest Post, large preview -->
            <div class="col-sm-12 blog-preview-item blog-preview-most-recent">
              <!-- Ribbon from: http://livetools.uiparade.com/ribbon-builder.html -->
              <div class="ribbon">
                <div class="ribbon-stitches-top"></div>
                <h1><strong class="ribbon-content">Newest!</strong></h1>
                <div class="ribbon-stitches-bottom"></div>
              </div>
              <div itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting">
                <a href="{{ url_for('blog.view_post', post_id=post.id, slug=post.slug) }}" itemprop="url">
                  <div class="caption">
                    <div class="caption-content">
                      <h1>Read More!</h1>
                    </div>
                  </div>

                  <h3 class="index-blog-title" itemprop="headline">{{ post.title }}</h3>
                  <p class="index-blog-caption" itemprop="description">
                    {{ post.body|safe|truncate(800)|markdown(skip_images=True, skip_links=True) }}
                  </p>
                  <small class="index-blog-meta">
                    {% with num_comments=post.comments|length %}
                      {{ num_comments }} comment {%- if num_comments != 1 %}s{%- endif -%}
                    {% endwith %} | {{ moment(post.created).calendar() }}
                  </small>
                  <meta itemprop="author" content="Kevin Crane"/>
                </a>
              </div>
            </div>
          </div>
        {% endwith %}
        <!-- Other recent posts -->
        {% for post_row in frontpage_posts[1:]|batch(3) %}
          <div class="row">
            {% for post in post_row %}
              <div class="col-sm-4 blog-preview-item">
                <div itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting">
                  <a href="{{ url_for('blog.view_post', post_id=post.id, slug=post.slug) }}" itemprop="url">
                    <div class="caption">
                      <div class="caption-content">
                        <h1>Read More!</h1>
                      </div>
                    </div>

                    <h3 class="index-blog-title" itemprop="headline">{{ post.title }}</h3>
                    <p class="index-blog-caption" itemprop="description">
                      {{ post.body|safe|truncate(255)|markdown(skip_images=True, skip_links=True) }}
                    </p>
                    <small class="index-blog-meta">
                      {% with num_comments=post.comments|length %}
                        {{ num_comments }} comment {%- if num_comments != 1 %}s{%- endif -%}
                      {% endwith %} | {{ moment(post.created).calendar() }}
                    </small>
                    <meta itemprop="author" content="Kevin Crane"/>
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="col-sm-12 text-center">
          <h3><a href="{{ url_for('blog.index') }}" class="underline-link" itemprop="url">See More Posts!</a></h3>
        </div>
      {% else %}
        <h3>No Posts Found... :(</h3>
      {% endif %}
    </div>
  </section>

  <!-- Projects -->
  <section id="index-project-preview">
    <div class="row">
      <div class="col-sm-12">
        <hr class="star-primary"/>
        <h2 class="text-center">Projects</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-2">
        <p>
          I haven't bothered to host anything useful here yet, but I will! Until then, go look at the stuff I've already
          posted on Github! Or things I've done before on LinkedIn! And check the link below for the eventual fun!
        </p>
      </div>
      <div class="col-sm-2 text-center">
        <a target="_blank" href="http://www.github.com/kevincrane" class="social-navbar" title="Github">
          <i class="fa fa-brands fa-github"></i>
        </a>
      </div>
      <div class="col-sm-2 text-center">
        <a target="_blank" href="https://www.linkedin.com/in/thekevincrane" class="social-navbar" title="LinkedIn">
          <i class="fa fa-brands fa-linkedin"></i>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3><a href="{{ url_for('base.projects') }}" class="underline-link" itemprop="significantLink">
          See More Projects!
        </a></h3>
      </div>
    </div>
  </section>

  <!-- About Me -->
  <section id="index-aboutme-preview">
    <div class="row">
      <div class="col-sm-12">
        <hr class="star-primary"/>
        <h2 class="text-center">About Me!</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <ul>
          <li>Coding wordsmith</li>
          <li>Regular kind of wordsmith</li>
          <li>USC Trojan forever</li>
          <li>Carnegie Mellon Tartan sometimes</li>
          <li>Cat lover and tex-mex enthusiast</li>
          <li>And if you just came here looking for a resume,
            <a href="{{ url_for('static', filename='Kevin-Crane-Resume.pdf') }}" class="underline-link" target="_blank">look no further</a>!</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <h3 class="text-center"><a href="{{ url_for('base.about') }}" class="underline-link" itemprop="significantLink">
        See More About Me!
      </a></h3>
    </div>
  </section>
  <meta itemprop="author" content="Kevin Crane"/>
</div>
{% endblock %}

app/templates/post.html
<!-- Extends base layout -->
{% extends "base_blog.html" %}
{% set active_page = "index" %}
{% import "_forms.html" as forms %}

{% block blog_main %}
  <h2 class="post-title">{{ post.title }}</h2>
  <p class="post-body">{{ post.body|safe|markdown }}</p>
  <small class="post-created">Created <i>{{ moment(post.created).calendar() }}</i></small>
  <hr/>

  <!-- Comments -->
  <h3>Comments</h3>
  {% if post.comments %}
    {% for comment in post.comments %}
      <p>{{ comment.body }}</p>
      <p>- <strong>{{ comment.author }}</strong> - <small>{{ moment(comment.created).calendar() }}</small></p>
      {{ comment.text }}
    {% endfor %}
  {% else %}
    <p><i>No Comments...</i></p>
  {% endif %}

  <hr>
  <h2>Add a comment</h2>
  <form action="" method="post">
    {{ forms.render(form) }}
    <div class="actions">
      <input type="submit" class="btn primary" value="comment">
    </div>
  </form>


  <!-- Previous page -->
  {% if prev_page %}
    <p><a href="{{ url_for('.index', page=prev_page) }}"><< Back to the rest.</a>
      {% else %}
    <p><a href="{{ url_for('.index') }}"><< Back to the rest</a>
  {% endif %}
{% endblock %}

{% block js %}
  <script type="text/javascript">
    $(document).ready(function () {
      $('pre code').each(function (i, e) {
        hljs.highlightBlock(e)
      });
    });
  </script>
{% endblock %}

app/templates/projects.html
<!-- Extends base layout -->
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}
  <h3>Projects</h3>
  <h5>To be added later!</h5>
  <ul>
    <li>
      Anything web dev-y that I want to show off (basically nothing so far because web development
      is boring and I'm not an artist)
    </li>
    <li>
      Links to code or demos for really cool back-end projects. This is the real shit because you have real
      flexibility and creativity for making something awesome and fun. It's just not usually good for normal people.
    </li>
  </ul>
  <hr class="star-primary"/>
{% endblock %}